In [1]:
import pandas as pd
import os 
import sys

In [2]:
os.chdir(r"C:\Users\Jack Wright\Documents\GitHub\sevLandsPublicData\dynamic_win_probability")

In [3]:
current_dir = os.getcwd()
funcs_dir = os.path.join(current_dir, 'funcs')
if funcs_dir not in sys.path:
    sys.path.append(funcs_dir)

In [4]:
from transform_row_to_turns import transform_row_to_turns
from get_input_columns import get_input_columns
from load_id_to_wr_mapping import load_id_to_wr_mapping
from load_id_to_wr_turn_mapping import load_id_to_wr_turn_mapping

In [5]:
input_columns = get_input_columns(num_turns = 20)

In [6]:
data = pd.read_csv(r'..\data\replay_data\replay_data_public.DSK.PremierDraft.csv', usecols = input_columns,  nrows = 10)

In [7]:
data

,draft_id,on_play,num_turns,won,user_turn_1_eot_user_cards_in_hand,user_turn_1_eot_user_lands_in_play,user_turn_1_eot_user_creatures_in_play,user_turn_1_eot_user_non_creatures_in_play,user_turn_1_eot_user_life,oppo_turn_1_eot_oppo_cards_in_hand,...,user_turn_20_eot_user_cards_in_hand,user_turn_20_eot_user_lands_in_play,user_turn_20_eot_user_creatures_in_play,user_turn_20_eot_user_non_creatures_in_play,user_turn_20_eot_user_life,oppo_turn_20_eot_oppo_cards_in_hand,oppo_turn_20_eot_oppo_lands_in_play,oppo_turn_20_eot_oppo_creatures_in_play,oppo_turn_20_eot_oppo_non_creatures_in_play,oppo_turn_20_eot_oppo_life
0,53401b113a4f425fa26e60edd314dd27,True,5,True,92217|92181|92219|92216|90190|90190,90189,NaN,NaN,20.0,7.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
1,53401b113a4f425fa26e60edd314dd27,False,9,False,92217|92216|92181|90190|92188|92219|90190,90189,NaN,NaN,20.0,6.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
2,53401b113a4f425fa26e60edd314dd27,True,11,False,92219|90190|92188|92216|90189|92167,90189,NaN,NaN,20.0,7.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
3,53401b113a4f425fa26e60edd314dd27,False,11,False,90190|90190|92236|90190|92206|90190|92217,90189,NaN,NaN,20.0,5.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
4,d26766b56fd14670ba60c2604bcd457b,False,12,False,92068|92092|92131|90187|92309|90187|92149,90188,NaN,NaN,20.0,6.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
5,d26766b56fd14670ba60c2604bcd457b,False,8,True,90188|92119|92122|92140|92073|90187|90188,90188,NaN,NaN,20.0,6.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
6,d26766b56fd14670ba60c2604bcd457b,False,10,True,90187|92309|90187|92144|92127|90187|92094,90188,NaN,NaN,20.0,5.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
7,d26766b56fd14670ba60c2604bcd457b,False,8,False,90188|92101|90188|92309|90187|92311|90187,90187,NaN,NaN,20.0,5.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
8,d26766b56fd14670ba60c2604bcd457b,True,7,True,90187|90188|92311|92119|92122,90188,NaN,NaN,20.0,7.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0
9,d26766b56fd14670ba60c2604bcd457b,True,7,True,92094|92140|92149|90187|92113|90188,90188,NaN,NaN,20.0,6.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0

In [8]:
sample_row = data.iloc[0]   
for key , value in sample_row.items():
    print(key, value)

draft_id 53401b113a4f425fa26e60edd314dd27
on_play True
num_turns 5
won True
user_turn_1_eot_user_cards_in_hand 92217|92181|92219|92216|90190|90190
user_turn_1_eot_user_lands_in_play 90189
user_turn_1_eot_user_creatures_in_play nan
user_turn_1_eot_user_non_creatures_in_play nan
user_turn_1_eot_user_life 20.0
oppo_turn_1_eot_oppo_cards_in_hand 7.0
oppo_turn_1_eot_oppo_lands_in_play 92370
oppo_turn_1_eot_oppo_creatures_in_play nan
oppo_turn_1_eot_oppo_non_creatures_in_play nan
oppo_turn_1_eot_oppo_life 20.0
user_turn_2_eot_user_cards_in_hand 92231|92217|92219|92216|90190
user_turn_2_eot_user_lands_in_play 90190|90189
user_turn_2_eot_user_creatures_in_play 92181.0
user_turn_2_eot_user_non_creatures_in_play nan
user_turn_2_eot_user_life 20.0
oppo_turn_2_eot_oppo_cards_in_hand 6.0
oppo_turn_2_eot_oppo_lands_in_play 92379|92370
oppo_turn_2_eot_oppo_creatures_in_play 92339.0
oppo_turn_2_eot_oppo_non_creatures_in_play nan
oppo_turn_2_eot_oppo_life 20.0
user_turn_3_eot_user_cards_in_hand 90189|92231|92217|92219
user_turn_3_eot_user_lands_in_play 90190|90190|90189
user_turn_3_eot_user_creatures_in_play 92216|92234
user_turn_3_eot_user_non_creatures_in_play nan
user_turn_3_eot_user_life 20.0
oppo_turn_3_eot_oppo_cards_in_hand 5.0
oppo_turn_3_eot_oppo_lands_in_play 92379|92379|92370
oppo_turn_3_eot_oppo_creatures_in_play 92339
oppo_turn_3_eot_oppo_non_creatures_in_play nan
oppo_turn_3_eot_oppo_life 14.0
user_turn_4_eot_user_cards_in_hand 92217|92219
user_turn_4_eot_user_lands_in_play 90189|90190|90190|90189
user_turn_4_eot_user_creatures_in_play 92337|92234
user_turn_4_eot_user_non_creatures_in_play 92231
user_turn_4_eot_user_life 17.0
oppo_turn_4_eot_oppo_cards_in_hand 4.0
oppo_turn_4_eot_oppo_lands_in_play 92381|92379|92379|92370
oppo_turn_4_eot_oppo_creatures_in_play 92226|92339
oppo_turn_4_eot_oppo_non_creatures_in_play nan
oppo_turn_4_eot_oppo_life 8.0
user_turn_5_eot_user_cards_in_hand 92217
user_turn_5_eot_user_lands_in_play 90189|90190|90190|90189
user_turn_5_eot_user_creatures_in_play 92212|92337|92234
user_turn_5_eot_user_non_creatures_in_play 92219|92231
user_turn_5_eot_user_life 14.0
oppo_turn_5_eot_oppo_cards_in_hand 0.0
oppo_turn_5_eot_oppo_lands_in_play nan
oppo_turn_5_eot_oppo_creatures_in_play nan
oppo_turn_5_eot_oppo_non_creatures_in_play nan
oppo_turn_5_eot_oppo_life 0.0
user_turn_6_eot_user_cards_in_hand nan
user_turn_6_eot_user_lands_in_play nan
user_turn_6_eot_user_creatures_in_play nan
user_turn_6_eot_user_non_creatures_in_play nan
user_turn_6_eot_user_life 0.0
oppo_turn_6_eot_oppo_cards_in_hand 0.0
oppo_turn_6_eot_oppo_lands_in_play nan
oppo_turn_6_eot_oppo_creatures_in_play nan
oppo_turn_6_eot_oppo_non_creatures_in_play nan
oppo_turn_6_eot_oppo_life 0.0
user_turn_7_eot_user_cards_in_hand nan
user_turn_7_eot_user_lands_in_play nan
user_turn_7_eot_user_creatures_in_play nan
user_turn_7_eot_user_non_creatures_in_play nan
user_turn_7_eot_user_life 0.0
oppo_turn_7_eot_oppo_cards_in_hand 0.0
oppo_turn_7_eot_oppo_lands_in_play nan
oppo_turn_7_eot_oppo_creatures_in_play nan
oppo_turn_7_eot_oppo_non_creatures_in_play nan
oppo_turn_7_eot_oppo_life 0.0
user_turn_8_eot_user_cards_in_hand nan
user_turn_8_eot_user_lands_in_play nan
user_turn_8_eot_user_creatures_in_play nan
user_turn_8_eot_user_non_creatures_in_play nan
user_turn_8_eot_user_life 0.0
oppo_turn_8_eot_oppo_cards_in_hand 0.0
oppo_turn_8_eot_oppo_lands_in_play nan
oppo_turn_8_eot_oppo_creatures_in_play nan
oppo_turn_8_eot_oppo_non_creatures_in_play nan
oppo_turn_8_eot_oppo_life 0.0
user_turn_9_eot_user_cards_in_hand nan
user_turn_9_eot_user_lands_in_play nan
user_turn_9_eot_user_creatures_in_play nan
user_turn_9_eot_user_non_creatures_in_play nan
user_turn_9_eot_user_life 0.0
oppo_turn_9_eot_oppo_cards_in_hand 0.0
oppo_turn_9_eot_oppo_lands_in_play nan
oppo_turn_9_eot_oppo_creatures_in_play nan
oppo_turn_9_eot_oppo_non_creatures_in_play nan
oppo_turn_9_eot_oppo_life 0.0
user_turn_10_eot_user_cards_in_hand nan
user_turn_10_eot_user_lands_in_play nan
user_turn_10_eot_user_creatures_in_play nan
user_turn_10_eot_user_non_creatures_in_play nan
user_turn_10_eot_user_life 0.0
oppo_turn_10_eot_oppo_cards_in_hand 0.0
oppo_turn_10_eot_oppo_lands_in_play nan
oppo_turn_10_eot_oppo_creatures_in_play nan
oppo_turn_10_eot_oppo_non_creatures_in_play nan
oppo_turn_10_eot_oppo_life 0.0
user_turn_11_eot_user_cards_in_hand nan
user_turn_11_eot_user_lands_in_play nan
user_turn_11_eot_user_creatures_in_play nan
user_turn_11_eot_user_non_creatures_in_play nan
user_turn_11_eot_user_life 0.0
oppo_turn_11_eot_oppo_cards_in_hand 0.0
oppo_turn_11_eot_oppo_lands_in_play nan
oppo_turn_11_eot_oppo_creatures_in_play nan
oppo_turn_11_eot_oppo_non_creatures_in_play nan
oppo_turn_11_eot_oppo_life 0.0
user_turn_12_eot_user_cards_in_hand nan
user_turn_12_eot_user_lands_in_play nan
user_turn_12_eot_user_creatures_in_play nan
user_turn_12_eot_user_non_creatures_in_play nan
user_turn_12_eot_user_life 0.0
oppo_turn_12_eot_oppo_cards_in_hand 0.0
oppo_turn_12_eot_oppo_lands_in_play nan
oppo_turn_12_eot_oppo_creatures_in_play nan
oppo_turn_12_eot_oppo_non_creatures_in_play nan
oppo_turn_12_eot_oppo_life 0.0
user_turn_13_eot_user_cards_in_hand nan
user_turn_13_eot_user_lands_in_play nan
user_turn_13_eot_user_creatures_in_play nan
user_turn_13_eot_user_non_creatures_in_play nan
user_turn_13_eot_user_life 0.0
oppo_turn_13_eot_oppo_cards_in_hand 0.0
oppo_turn_13_eot_oppo_lands_in_play nan
oppo_turn_13_eot_oppo_creatures_in_play nan
oppo_turn_13_eot_oppo_non_creatures_in_play nan
oppo_turn_13_eot_oppo_life 0.0
user_turn_14_eot_user_cards_in_hand nan
user_turn_14_eot_user_lands_in_play nan
user_turn_14_eot_user_creatures_in_play nan
user_turn_14_eot_user_non_creatures_in_play nan
user_turn_14_eot_user_life 0.0
oppo_turn_14_eot_oppo_cards_in_hand 0.0
oppo_turn_14_eot_oppo_lands_in_play nan
oppo_turn_14_eot_oppo_creatures_in_play nan
oppo_turn_14_eot_oppo_non_creatures_in_play nan
oppo_turn_14_eot_oppo_life 0.0
user_turn_15_eot_user_cards_in_hand nan
user_turn_15_eot_user_lands_in_play nan
user_turn_15_eot_user_creatures_in_play nan
user_turn_15_eot_user_non_creatures_in_play nan
user_turn_15_eot_user_life 0.0
oppo_turn_15_eot_oppo_cards_in_hand 0.0
oppo_turn_15_eot_oppo_lands_in_play nan
oppo_turn_15_eot_oppo_creatures_in_play nan
oppo_turn_15_eot_oppo_non_creatures_in_play nan
oppo_turn_15_eot_oppo_life 0.0
user_turn_16_eot_user_cards_in_hand nan
user_turn_16_eot_user_lands_in_play nan
user_turn_16_eot_user_creatures_in_play nan
user_turn_16_eot_user_non_creatures_in_play nan
user_turn_16_eot_user_life 0.0
oppo_turn_16_eot_oppo_cards_in_hand 0.0
oppo_turn_16_eot_oppo_lands_in_play nan
oppo_turn_16_eot_oppo_creatures_in_play nan
oppo_turn_16_eot_oppo_non_creatures_in_play nan
oppo_turn_16_eot_oppo_life 0.0
user_turn_17_eot_user_cards_in_hand nan
user_turn_17_eot_user_lands_in_play nan
user_turn_17_eot_user_creatures_in_play nan
user_turn_17_eot_user_non_creatures_in_play nan
user_turn_17_eot_user_life 0.0
oppo_turn_17_eot_oppo_cards_in_hand 0.0
oppo_turn_17_eot_oppo_lands_in_play nan
oppo_turn_17_eot_oppo_creatures_in_play nan
oppo_turn_17_eot_oppo_non_creatures_in_play nan
oppo_turn_17_eot_oppo_life 0.0
user_turn_18_eot_user_cards_in_hand nan
user_turn_18_eot_user_lands_in_play nan
user_turn_18_eot_user_creatures_in_play nan
user_turn_18_eot_user_non_creatures_in_play nan
user_turn_18_eot_user_life 0.0
oppo_turn_18_eot_oppo_cards_in_hand 0.0
oppo_turn_18_eot_oppo_lands_in_play nan
oppo_turn_18_eot_oppo_creatures_in_play nan
oppo_turn_18_eot_oppo_non_creatures_in_play nan
oppo_turn_18_eot_oppo_life 0.0
user_turn_19_eot_user_cards_in_hand nan
user_turn_19_eot_user_lands_in_play nan
user_turn_19_eot_user_creatures_in_play nan
user_turn_19_eot_user_non_creatures_in_play nan
user_turn_19_eot_user_life 0.0
oppo_turn_19_eot_oppo_cards_in_hand 0.0
oppo_turn_19_eot_oppo_lands_in_play nan
oppo_turn_19_eot_oppo_creatures_in_play nan
oppo_turn_19_eot_oppo_non_creatures_in_play nan
oppo_turn_19_eot_oppo_life 0.0
user_turn_20_eot_user_cards_in_hand nan
user_turn_20_eot_user_lands_in_play nan
user_turn_20_eot_user_creatures_in_play nan
user_turn_20_eot_user_non_creatures_in_play nan
user_turn_20_eot_user_life 0.0
oppo_turn_20_eot_oppo_cards_in_hand 0.0
oppo_turn_20_eot_oppo_lands_in_play nan
oppo_turn_20_eot_oppo_creatures_in_play nan
oppo_turn_20_eot_oppo_non_creatures_in_play nan
oppo_turn_20_eot_oppo_life 0.0

In [9]:
df_dynamic = transform_row_to_turns(data.iloc[0], dynamic_winrate = True)

In [10]:
cols = [col for col in df_dynamic.columns.tolist() if 'creature' in col]

In [11]:
df_static  = transform_row_to_turns(data.iloc[0], dynamic_winrate = False)
df_static[cols]

,user_creatures_1,user_creatures_2,user_creatures_3,user_creatures_4,user_creatures_5,user_creatures_6,user_creatures_7,user_creatures_8,user_creatures_9,user_creatures_10,...,oppo_non_creatures_11,oppo_non_creatures_12,oppo_non_creatures_13,oppo_non_creatures_14,oppo_non_creatures_15,oppo_non_creatures_16,oppo_non_creatures_17,oppo_non_creatures_18,oppo_non_creatures_19,oppo_non_creatures_20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.558,0.560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.548,0.560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.563,0.548,0.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
cols = [col for col in df_dynamic.columns.tolist() if 'creature' in col]
df_dynamic[cols]

,user_creatures_1,user_creatures_2,user_creatures_3,user_creatures_4,user_creatures_5,user_creatures_6,user_creatures_7,user_creatures_8,user_creatures_9,user_creatures_10,...,oppo_non_creatures_11,oppo_non_creatures_12,oppo_non_creatures_13,oppo_non_creatures_14,oppo_non_creatures_15,oppo_non_creatures_16,oppo_non_creatures_17,oppo_non_creatures_18,oppo_non_creatures_19,oppo_non_creatures_20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.558000,0.593006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.548000,0.593006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.577147,0.611786,0.586741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
sample_row['user_turn_3_eot_user_creatures_in_play']

'92216|92234'

In [14]:
wr_mapping_static = load_id_to_wr_mapping()

In [15]:
wr_mapping_static[92216]

0.5579999999999999

In [16]:
wr_mapping_turn = load_id_to_wr_turn_mapping()

: